### ISSUE TITLE
[TC][BE] Set-up tables/schemas

### ISSUE THREAD

**Issue by tianyan-zhu** [shizuko-akamoto/Trecipe#13]
Story Points: 2

- [ ] Name
- [ ] Date of create (timestamp)
- [ ] Last modified
- [ ] Picture
- [ ] Owner
- [ ] (Collaborators)
- [ ] privacy setting
- [ ] Card ID [CardID + Destination (separate table)]

**Comment by shumalll** [comment]
Setup a new user Team2Admins in my atlas collection with dbAdmin access to _Trecipe_ collection. 
Use const uri = "mongodb+srv://Team2Admins:Trecipe@sandbox-l7lbk.mongodb.net/Trecipe?retryWrites=true&w=majority"; as connection string to connect to the collection.


Proposed schema here: https://docs.google.com/document/d/1Aikrv_0HMk63qI-ELRfoplBmFtjFA4kRdjIt0DEoYEc, feel free to add  any comments/feedbacks.

**Comment by shizuko-akamoto** [comment]
Left some comments to the google doc!
