### ISSUE TITLE
[TP][FE] Design for Trecipe Page

### ISSUE THREAD

**Issue by tianyan-zhu** [shizuko-akamoto/Trecipe#14]
Story Point: 1

**Comment by shizuko-akamoto** [comment]
Added TC page design to google drive.
For reference, attaching them here as well:
[TC_page.pdf](https://github.com/shizuko-akamoto/Trecipe/files/4725859/TC_page.pdf)
[TC_paage2.pdf](https://github.com/shizuko-akamoto/Trecipe/files/4725858/TC_paage2.pdf) (Outline version)
