### ISSUE TITLE
[TP][BE] Investigate destination/map api

### ISSUE THREAD

**Issue by tianyan-zhu** [shizuko-akamoto/Trecipe#24]
Story Points: 3

**Comment by shumalll** [comment]
Updated result here:
https://docs.google.com/document/d/1mknWsjNj7LK7rdV7aw5-PPfuXI0HiN4B45KZevwhd6k

@shizuko-akamoto @tianyan-zhu @knox153  
Let me know if it looks good or there's anything you want me to look further into.

**Comment by knox153** [comment]
Looks great, seems like it can do everything we wanted to :ok_hand:

**Comment by shizuko-akamoto** [comment]
Thanks for investigating!! Glad we're also able to replace TripAdvisor with Google Dest api
